server:
  port: 8080

spring:
  application:
   name: gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1